name: Daily Release
on:
  push:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Changes

  changes:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      updates: ${{steps.changes.outputs.any == 'true'}}
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.1 # Optional fallback tag to use when no tag can be found
      # Use paths-filter to determine which paths have changes
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.previoustag.outputs.tag }}
          filters: |
            any: "**"

  release:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{needs.changes.outputs.updates == 'true'}}
    steps:
      - uses: actions/checkout@v2
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
