name: Nightly Action
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6

  on-success:
    needs: check-diff
    runs-on: ubuntu-latest
    if: needs.check-diff.outputs.diff
    steps:
      - run: echo ${{ needs.check-diff.outputs.diff }}
