name: Nightly Action
on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Check if the changed status of py is true
      updates: steps.changes.outputs.any == 'true'
      previoustag: steps.previoustag.outputs.tag
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      # Use paths-filter to determine which paths have changes
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.previoustag.outputs.tag }}
          filters: |
            any: "**"
  on-success:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.any }}
    steps:
      - run: echo Changes
